### ISSUE TITLE
Possibly Incompatible with Jupyter Console 4.1.0???

### ISSUE THREAD

**Issue by prncevince** [nvictus/SublimeIPython#9]
Hey. I'm wondering how to make this work for the latest version of IPython.
I've attached screen shots to show the error that is popping up, and to give you an idea of what I'm working with. I accessed my IPython REPL through the Command Pallet with "SublimeREPL: Python - IPython". 

The error is "ImportError: No module named IPython.kernel". I get this when I press **cmd+enter** on my Mac in attempt to evaluate a cell in the python file named "stupid.py". "stupid.py" has the syntax highlighting set to IPython. Next to "stupid.py", I have the IPython REPL open (which I opened first), and when I give the **cmd+enter** command to evaluate a cell in "stupid.py", nothing is run in the IPython REPL.

Also, the **cmd+"."** command works fine. Let me know if you can figure out what's up with the Error message. Thanks!
<img width="1150" alt="screen shot 2016-03-08 at 10 42 57 pm" src="https://cloud.githubusercontent.com/assets/17718313/13625226/4e3382ba-e583-11e5-8b71-9b6de1d8be67.png">
<img width="603" alt="screen shot 2016-03-08 at 10 43 21 pm" src="https://cloud.githubusercontent.com/assets/17718313/13625227/4e3acffc-e583-11e5-9ec6-97f31c3403ee.png">
<img width="1148" alt="screen shot 2016-03-08 at 10 43 58 pm" src="https://cloud.githubusercontent.com/assets/17718313/13625228/4e3affae-e583-11e5-8e8f-2a413995f4e9.png">

**Comment by nvictus** [comment]
Hi there! Yes, you're right. I wrote the code cell executor for an older version of IPython and way before the Jupyter split and the API used to access the kernel is deprecated. I'll have to take a look at the new way to do it. I should note that I haven't been working on the project in quite some time. I'm pretty busy these days, but I'm actually at a Jupyter event in Boston today, so I might see if this project can be revived!

**Comment by nvictus** [comment]
Got it working. Give the devel branch a try: 2604d2d

**Comment by prncevince** [comment]
Hi, thanks for the update. Enjoy the Jupyter event! I replaced the master branch with the devel branch in my _Packages_ directory of Sublime. But it still seems that the script can't access the jupyter_client module. 
<img width="1196" alt="screen shot 2016-03-17 at 4 02 29 pm" src="https://cloud.githubusercontent.com/assets/17718313/13859442/d59068f4-ec59-11e5-98df-6bdc124ab7fc.png">

**Comment by nvictus** [comment]
Do you know which Python executable on your system SublimeREPL is using? The plugin is using the default `/usr/bin/env python` which doesn't seem to have jupyter installed or available for import.

Note that I had added an option to specify a virtualenv, but this should be changed to have an option or config file that lets you specify any custom python executable path.

UPDATE: I replaced the virtualenv setting with a custom `python_executable` setting in `IPython.sublime-settings`. You can replace it with the value of `sys.executable` in your IPython REPL or any python that has jupyter_client installed. 0544923

**Comment by prncevince** [comment]
Let's dumb this down a little bit. I run Python through my anaconda package. In anaconda there are two different jupyter_client folders. Are you saying that I should replace `python_executable` in the `IPython.sublime-settings` file with something like `"usr/anaconda/lib/python2.7/site-packages"` where site-packages is the folder that jupyter_client is in? (again, this is where one of the jupiter_client folder's is located, the other is in `"usr/anaconda/pkgs/jupyter_client-4.1.1-py27_0/lib/python2.7/site-packages/jupyter_client"`) 

If so this still gets the `ImportError: No module named jupyter_client`. Or maybe I need to save the .py file that I am running **cmd+enter** on into a different directory? The directory that my .py file is saved under is `"/Users/usr"`, and thus the cwd of the IPython REPL is this as well. 

<img width="334" alt="screen shot 2016-03-19 at 8 20 36 pm" src="https://cloud.githubusercontent.com/assets/17718313/13902074/355a0fd0-ee10-11e5-9515-c5e26e3ad456.png">

**Comment by nvictus** [comment]
Nope, you don't want to specify the site-packages folder, rather the path to a Python binary that has Jupyter installed. Your machine probably has several Pythons installed (including the one embedded in SublimeText!)

>  I run Python through my anaconda package. 

Great! Then your python executable should likely be something like `/Users/usr/anaconda/bin/python'. To verify that's what your SublimeREPL uses, enter the following on your console prompt:

```
>>> import sys
>>> sys.executable
```

That's the path you want. Also, rather than edit the Default settings file inside the package, it is often recommended to create a user override file, which you can do by clicking on the Preferences menu --> Package Settings --> IPython --> Settings -- User. Then place the following text in it and save:

```
{
    "python_executable": "<path obtained as described above>"
}
```

>  Or maybe I need to save the .py file that I am running cmd+enter on into a different directory?

No, that shouldn't be necessary.

**Comment by prncevince** [comment]
Thank you for your quick responses! So I did everything as you describe above. Now when I execute a cell, the console says Out [number]: succeeded!

However, there is no corresponding output in the REPL. I am executing a simple print statement in my code cells. What am I missing here?

**Comment by nvictus** [comment]
Code does get executed in the kernel, but unfortunately, it won't send the stdout to the REPL. That's actually issue #4. The plugin does report stderr inside the Sublime console, but I never got around to completely figuring out how to work with the messaging protocol to reliably print stdout. To be fair, I've mostly used this plugin to interact with the matplotlib gui. Sorry the plugin isn't more complete; I should leave a disclaimer in the README. 

[This repo](https://github.com/nvictus/knitpy/blob/master/knitpy/knitpy.py#L434) seems to implement the full flow of executing lines of code and listening on the shell and iopub sockets to get the appropriate responses. I'd love to give it a go myself, but I'm pressed for time for the near future. In case you feel like hacking around with it and making a PR, I'd be happy to review.

Here's also a link to the messaging spec, in case you're interested.
https://jupyter-client.readthedocs.org/en/latest/messaging.html

**Comment by prncevince** [comment]
It still all works great for my purposes. If I get enough experience with writing source in the future I might look into it. Thank you for the all knowledge Pokémon master.
